-- DashboardMon schema. Jalankan sekali di Supabase SQL Editor, lalu jalankan seed.sql.

create table if not exists public.usulan (
  kode text primary key,
  judul text not null,
  unor_kode text not null,
  unit_terdampak text[] not null default '{}',
  jenis_perubahan text not null,
  tahap_saat_ini text not null,
  posisi_bola text not null,
  putaran integer not null default 1,
  tanggal_masuk_tahap date not null,
  tanggal_usulan_awal date not null,
  tanggal_usulan_awal_edited_at date,
  tanggal_usulan_awal_edited_by text,
  status text not null default 'aktif',
  catatan_terakhir text not null default '',
  deleted_at date,
  deleted_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.dokumen (
  id bigint generated by default as identity primary key,
  usulan_kode text not null references public.usulan (kode),
  putaran integer not null,
  jenis text not null,
  versi integer not null default 1,
  tanggal_terima date not null,
  status_validasi text not null default 'diterima',
  catatan_validasi text not null default '',
  validator_nama text not null default '',
  tanggal_validasi date
);

-- Urutan id = urutan asli pencatatan; aplikasi bergantung pada urutan ini.
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  usulan_kode text not null references public.usulan (kode),
  dari_tahap text not null,
  ke_tahap text not null,
  dari_posisi_bola text not null,
  ke_posisi_bola text not null,
  putaran integer not null,
  tanggal date not null,
  keterangan text not null,
  oleh_siapa text not null,
  manual boolean not null default false,
  tanggal_edited_at date,
  tanggal_edited_by text
);

create index if not exists dokumen_usulan_kode_idx on public.dokumen (usulan_kode);
create index if not exists logs_usulan_kode_idx on public.logs (usulan_kode);

-- Nomor urut kode usulan, dipakai bersama oleh semua pengguna.
create sequence if not exists public.usulan_seq;

create or replace function public.next_usulan_seq()
returns bigint
language sql
security definer
set search_path = public
as $$ select nextval('public.usulan_seq') $$;

grant execute on function public.next_usulan_seq() to anon, authenticated;

-- Akses terbuka (belum ada login): baca, tambah, dan ubah diizinkan; hapus tidak,
-- karena aplikasi hanya melakukan soft delete (deleted_at).
alter table public.usulan enable row level security;
alter table public.dokumen enable row level security;
alter table public.logs enable row level security;

do $$
declare t text;
begin
  foreach t in array array['usulan', 'dokumen', 'logs'] loop
    execute format('drop policy if exists "open select" on public.%I', t);
    execute format('drop policy if exists "open insert" on public.%I', t);
    execute format('drop policy if exists "open update" on public.%I', t);
    execute format('create policy "open select" on public.%I for select to anon, authenticated using (true)', t);
    execute format('create policy "open insert" on public.%I for insert to anon, authenticated with check (true)', t);
    execute format('create policy "open update" on public.%I for update to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;
